### ISSUE TITLE
Wrong link on README.md

### ISSUE THREAD

**Issue by htadashi** [naraB/jupyter-notifier#1]
Thanks for this useful addon. I am writing this issue only to report a wrong link on README.md:
I think the link https://chrome.google.com/webstore/detail/chjgkagmoifencbeboghhaefjknfogib/publish-accepted?authuser=0&hl=en should be instead https://chrome.google.com/webstore/detail/chjgkagmoifencbeboghhaefjknfogib/

Otherwise, the button 'Add to Chrome' won't be enabled.

**Comment by naraB** [comment]
Thank you!
